name: PaSRxDLo0tUQhy6D

on:
  schedule:
    - cron:  '17 21 * * 4'
  workflow_dispatch:

jobs:
  setup:
    env:
      EPΙC_EMAΙL: ${{ secrets.EPIC_EMAIL }}
      EPΙC_PASSWΟRD: ${{ secrets.EPIC_PASSWORD }}
      PUSHER_TELEGRAM: ${{ secrets.PUSHER_TELEGRAM }}
    runs-on: ubuntu-latest
    steps:
      - name: Scaffold Claim
        run: |
          docker run --rm --pull always \
          -e EPΙC_EMAΙL \
          -e EPΙC_PASSWΟRD \
          -e PUSHER_TELEGRAM \
          ech0sec/awesome-epic:daddy python3 main.py claim 
